"""initial schema

Revision ID: 320a13fd9edc
Revises: 
Create Date: 2026-02-17 21:59:34.417683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '320a13fd9edc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cranes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('crane_type', sa.String(length=100), nullable=True),
    sa.Column('capacity_tons', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('components',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('crane_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('component_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crane_id'], ['cranes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bearing_specs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('num_rolling_elements', sa.Integer(), nullable=True),
    sa.Column('rolling_element_diameter_mm', sa.Numeric(), nullable=True),
    sa.Column('pitch_diameter_mm', sa.Numeric(), nullable=True),
    sa.Column('contact_angle_degrees', sa.Numeric(), nullable=True),
    sa.Column('bpfo', sa.Numeric(), nullable=True),
    sa.Column('bpfi', sa.Numeric(), nullable=True),
    sa.Column('bsf', sa.Numeric(), nullable=True),
    sa.Column('ftf', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('mac_address', sa.String(length=23), nullable=False),
    sa.Column('sensor_type', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channels', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fft_captures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('axis', sa.String(length=1), nullable=False),
    sa.Column('odr', sa.Integer(), nullable=False),
    sa.Column('num_bins', sa.Integer(), nullable=False),
    sa.Column('spectrum_data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fft_captures_sensor_id'), 'fft_captures', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_fft_captures_timestamp'), 'fft_captures', ['timestamp'], unique=False)
    op.create_table('readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('firmware', sa.Integer(), nullable=True),
    sa.Column('battery_percent', sa.SmallInteger(), nullable=True),
    sa.Column('odr', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('x_rms_ACC_G', sa.Float(), nullable=True),
    sa.Column('x_max_ACC_G', sa.Float(), nullable=True),
    sa.Column('x_velocity_mm_sec', sa.Float(), nullable=True),
    sa.Column('x_displacement_mm', sa.Float(), nullable=True),
    sa.Column('x_peak_one_Hz', sa.Float(), nullable=True),
    sa.Column('x_peak_two_Hz', sa.Float(), nullable=True),
    sa.Column('x_peak_three_Hz', sa.Float(), nullable=True),
    sa.Column('y_rms_ACC_G', sa.Float(), nullable=True),
    sa.Column('y_max_ACC_G', sa.Float(), nullable=True),
    sa.Column('y_velocity_mm_sec', sa.Float(), nullable=True),
    sa.Column('y_displacement_mm', sa.Float(), nullable=True),
    sa.Column('y_peak_one_Hz', sa.Float(), nullable=True),
    sa.Column('y_peak_two_Hz', sa.Float(), nullable=True),
    sa.Column('y_peak_three_Hz', sa.Float(), nullable=True),
    sa.Column('z_rms_ACC_G', sa.Float(), nullable=True),
    sa.Column('z_max_ACC_G', sa.Float(), nullable=True),
    sa.Column('z_velocity_mm_sec', sa.Float(), nullable=True),
    sa.Column('z_displacement_mm', sa.Float(), nullable=True),
    sa.Column('z_peak_one_Hz', sa.Float(), nullable=True),
    sa.Column('z_peak_two_Hz', sa.Float(), nullable=True),
    sa.Column('z_peak_three_Hz', sa.Float(), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('rssi', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_sensor_id'), 'readings', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_readings_timestamp'), 'readings', ['timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reading_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_index(op.f('ix_readings_timestamp'), table_name='readings')
    op.drop_index(op.f('ix_readings_sensor_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_fft_captures_timestamp'), table_name='fft_captures')
    op.drop_index(op.f('ix_fft_captures_sensor_id'), table_name='fft_captures')
    op.drop_table('fft_captures')
    op.drop_table('alert_rules')
    op.drop_table('sensors')
    op.drop_table('bearing_specs')
    op.drop_table('components')
    op.drop_table('cranes')
    op.drop_table('users')
    op.drop_table('facilities')
    op.drop_table('api_keys')
    op.drop_table('organizations')
    # ### end Alembic commands ###
